# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mason McClelland
email: mcclelland.94@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio and Blog of Mason McClelland
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: mcclellandmsn
github_username:  mcclellandmsn

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
